# Generated by Django 5.1.3 on 2024-12-20 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookstatus_checkout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstatus',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_status', to='api.book'),
        ),
        migrations.AlterField(
            model_name='bookstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available'), (0, 'Not Available')]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_checkouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='checkout',
            unique_together={('user', 'book')},
        ),
    ]
