# Generated by Django 5.1.3 on 2024-12-22 20:52

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=accounts.fields.CaseInsensitiveEmailField(max_length=254, unique=True),
        ),
    ]
