# Generated by Django 5.1.3 on 2024-12-31 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Librarian', 'Librarian'), ('Administrator', 'Admin')], default='Member', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libraryuser', to='accounts.libraryrole'),
        ),
    ]
